#ifndef _CHIP8_ISA_REGISTERS_H_
#define _CHIP8_ISA_REGISTERS_H_

#include <defines.h>

typedef BYTE CHIP8_REGISTER;

#define CHIP8_REGISTER_R0  ( 0  )
#define CHIP8_REGISTER_R1  ( 1  )
#define CHIP8_REGISTER_R2  ( 2  )
#define CHIP8_REGISTER_R3  ( 3  )
#define CHIP8_REGISTER_R4  ( 4  )
#define CHIP8_REGISTER_R5  ( 5  )
#define CHIP8_REGISTER_R6  ( 6  )
#define CHIP8_REGISTER_R7  ( 7  )
#define CHIP8_REGISTER_R8  ( 8  )
#define CHIP8_REGISTER_R9  ( 9  )
#define CHIP8_REGISTER_R10 ( 10 )
#define CHIP8_REGISTER_R11 ( 11 )
#define CHIP8_REGISTER_R12 ( 12 )
#define CHIP8_REGISTER_R13 ( 13 )
#define CHIP8_REGISTER_R14 ( 14 )
#define CHIP8_REGISTER_R15 ( 15 )

#define CHIP8_REGISTER_FLAGS ( CHIP8_REGISTER_R15 )
#define CHIP8_REGISTER_COUNT ( 16 )

#endif // _CHIP8_ISA_REGISTERS_H_